{{- if .Values.services.sma.enabled }}
{{- $user := .Values.services.sma.datastores.sql.user -}}
{{- $password := .Values.services.sma.datastores.sql.password -}}
{{- $host := .Values.services.sma.datastores.sql.host | default "postgres-rw" -}}
{{- $port := .Values.services.sma.datastores.sql.port | default 5432 -}}
{{- $database := .Values.services.sma.datastores.sql.database -}}
{{- $dsn := printf "postgresql://%s:%s@%s:%d/%s?sslmode=disable" $user $password $host $port $database -}}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-sma
  name: {{ .Release.Name }}-sma
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  sql.dsn: {{ $dsn | b64enc }}
  sql.host: {{ $host | b64enc }}
  sql.port: {{ $port | toString | b64enc }}
  sql.user: {{ $user | b64enc }}
  sql.password: {{ $password | b64enc }}
  sql.database: {{ $database | b64enc }}
{{- end }} 