apiVersion: v1
kind: ConfigMap
metadata:
    name: cryptellation-credentials
data:
    # Exchanges
    binance.api_key: "{{ (.Values.credentials).exchanges.binance.api_key }}"
    binance.secret_key: "{{ (.Values.credentials).exchanges.binance.secret_key }}"
    
    # Temporal
    {{ $DEFAULT_TEMPORAL_ADDRESS := (print .Release.Name "-temporal-frontend." .Release.Namespace ".svc.cluster.local:7233") }}
    temporal.address: "{{ ((.Values.credentials).temporal).address | default $DEFAULT_TEMPORAL_ADDRESS }}"

    # Opentelemetry
    opentelemetry.grpc.endpoint: "{{ ((.Values.credentials).opentelemetry).grpc.endpoint }}"
