# Credentials represents the credentials for the Cryptellation system.
credentials:
  # Exchanges contains the API keys for various exchanges.
  exchanges:
    # Binance contains the Binance exchange API credentials.
    binance:
      # API key for Binance exchange.
      api_key: changeme
      # Secret key for Binance exchange.
      secret_key: changeme
  # OpenTelemetry contains the credentials for OpenTelemetry.
  opentelemetry:
    # gRPC endpoint configuration for OpenTelemetry.
    grpc:
      # Endpoint URL for OpenTelemetry gRPC server.
      endpoint:
  # Temporal contains the credentials for Temporal.
  temporal:
    # Address of the Temporal server.
    address: # Set by default to the Temporal service name in the same namespace (e.g., "temporal-frontend.cryptellation.svc.cluster.local:7233")

# Services contains the configuration for all Cryptellation services.
services: 
  # Backtests service configuration.
  backtests:
    # Enable or disable the backtests service.
    enabled: true
    # Image contains the image configuration.
    image:
      # Docker image repository for backtests service.
      repository: ghcr.io/cryptellation/backtests
      # Docker image tag for backtests service.
      tag: latest
      # Docker image pull policy for backtests service.
      pullPolicy: Always
    # Health contains the health check configuration.
    health:
      # Health check endpoint address for backtests service.
      address: ":9000"
    # Datastores contains the database connection strings.
    datastores:
      # SQL database configuration.
      sql:
        # Database host address.
        host: # Set by default to the Postgres service name in the same namespace (e.g., "postgres-rw")
        # Database port number.
        port: # Set by default to 5432, the default Postgres port
        # Database username.
        user: cryptellation
        # Database password.
        password: cryptellation
        # Database name.
        database: backtests
  # Candlesticks service configuration.
  candlesticks:
    # Enable or disable the candlesticks service.
    enabled: true
    # Image contains the image configuration.
    image:
      # Docker image repository for candlesticks service.
      repository: ghcr.io/cryptellation/candlesticks
      # Docker image tag for candlesticks service.
      tag: latest
      # Docker image pull policy for candlesticks service.
      pullPolicy: Always
    # Health contains the health check configuration.
    health:
      # Health check endpoint address for candlesticks service.
      address: ":9000"
    # Datastores contains the database connection strings.
    datastores:
      # SQL database configuration.
      sql:
        # Database host address.
        host: # Set by default to the Postgres service name in the same namespace (e.g., "postgres-rw")
        # Database port number.
        port: # Set by default to 5432, the default Postgres port
        # Database username.
        user: cryptellation
        # Database password.
        password: cryptellation
        # Database name.
        database: candlesticks
  # Exchanges service configuration.
  exchanges:
    # Enable or disable the exchanges service.
    enabled: true
    # Image contains the image configuration.
    image:
      # Docker image repository for exchanges service.
      repository: ghcr.io/cryptellation/exchanges
      # Docker image tag for exchanges service.
      tag: latest
      # Docker image pull policy for exchanges service.
      pullPolicy: Always
    # Health contains the health check configuration.
    health:
      # Health check endpoint address for exchanges service.
      address: ":9000"
    # Datastores contains the database connection strings.
    datastores:
      # SQL database configuration.
      sql:
        # Database host address.
        host: # Set by default to the Postgres service name in the same namespace (e.g., "postgres-rw")
        # Database port number.
        port: # Set by default to 5432, the default Postgres port
        # Database username.
        user: cryptellation
        # Database password.
        password: cryptellation
        # Database name.
        database: exchanges
  # Forwardtests service configuration.
  forwardtests:
    # Enable or disable the forwardtests service.
    enabled: true
    # Image contains the image configuration.
    image:
      # Docker image repository for forwardtests service.
      repository: ghcr.io/cryptellation/forwardtests
      # Docker image tag for forwardtests service.
      tag: latest
      # Docker image pull policy for forwardtests service.
      pullPolicy: Always
    # Health contains the health check configuration.
    health:
      # Health check endpoint address for forwardtests service.
      address: ":9000"
    # Datastores contains the database connection strings.
    datastores:
      # SQL database configuration.
      sql:
        # Database host address.
        host: # Set by default to the Postgres service name in the same namespace (e.g., "postgres-rw")
        # Database port number.
        port: # Set by default to 5432, the default Postgres port
        # Database username.
        user: cryptellation
        # Database password.
        password: cryptellation
        # Database name.
        database: forwardtests
  # SMA service configuration.
  sma:
    # Enable or disable the sma service.
    enabled: true
    # Image contains the image configuration.
    image:
      # Docker image repository for sma service.
      repository: ghcr.io/cryptellation/sma
      # Docker image tag for sma service.
      tag: latest
      # Docker image pull policy for sma service.
      pullPolicy: Always
    # Health contains the health check configuration.
    health:
      # Health check endpoint address for sma service.
      address: ":9000"
    # Datastores contains the database connection strings.
    datastores:
      # SQL database configuration.
      sql:
        # Database host address.
        host: # Set by default to the Postgres service name in the same namespace (e.g., "postgres-rw")
        # Database port number.
        port: # Set by default to 5432, the default Postgres port
        # Database username.
        user: cryptellation
        # Database password.
        password: cryptellation
        # Database name.
        database: sma
  # Ticks service configuration.
  ticks:
    # Enable or disable the ticks service.
    enabled: true
    # Image contains the image configuration.
    image:
      # Docker image repository for ticks service.
      repository: ghcr.io/cryptellation/ticks
      # Docker image tag for ticks service.
      tag: latest
      # Docker image pull policy for ticks service.
      pullPolicy: Always
    # Health contains the health check configuration.
    health:
      # Health check endpoint address for ticks service.
      address: ":9000"