{{ if .Values.cockroachdb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cockroachdb-initdb-config
data:
  temporal.sql: |
    -- Temporal user initialization
    CREATE USER IF NOT EXISTS temporal;
    ALTER USER temporal CREATEDB;

    -- Temporal database initialization
    CREATE DATABASE IF NOT EXISTS temporal;
    GRANT ALL PRIVILEGES ON DATABASE temporal TO temporal;
    USE temporal;
    GRANT ALL ON SCHEMA public TO temporal;

  cryptellation.sql: |
    -- Cryptellation user initialization
    CREATE USER IF NOT EXISTS cryptellation;
    ALTER USER cryptellation CREATEDB;

    -- Cryptellation Backtests database initialization
    CREATE DATABASE IF NOT EXISTS cryptellation_backtests;
    GRANT ALL PRIVILEGES ON DATABASE cryptellation_backtests TO cryptellation;
    USE cryptellation_backtests;
    GRANT ALL ON SCHEMA public TO cryptellation;

    -- Cryptellation Candlesticks database initialization
    CREATE DATABASE IF NOT EXISTS cryptellation_candlesticks;
    GRANT ALL PRIVILEGES ON DATABASE cryptellation_candlesticks TO cryptellation;
    USE cryptellation_candlesticks;
    GRANT ALL ON SCHEMA public TO cryptellation;

    -- Cryptellation Exchanges database initialization
    CREATE DATABASE IF NOT EXISTS cryptellation_exchanges;
    GRANT ALL PRIVILEGES ON DATABASE cryptellation_exchanges TO cryptellation;
    USE cryptellation_exchanges;
    GRANT ALL ON SCHEMA public TO cryptellation;

    -- Cryptellation Forwardtests database initialization
    CREATE DATABASE IF NOT EXISTS cryptellation_forwardtests;
    GRANT ALL PRIVILEGES ON DATABASE cryptellation_forwardtests TO cryptellation;
    USE cryptellation_forwardtests;
    GRANT ALL ON SCHEMA public TO cryptellation;

    -- Cryptellation SMA database initialization
    CREATE DATABASE IF NOT EXISTS cryptellation_sma;
    GRANT ALL PRIVILEGES ON DATABASE cryptellation_sma TO cryptellation;
    USE cryptellation_sma;
    GRANT ALL ON SCHEMA public TO cryptellation;

    -- Cryptellation Ticks database initialization
    CREATE DATABASE IF NOT EXISTS cryptellation_ticks;
    GRANT ALL PRIVILEGES ON DATABASE cryptellation_ticks TO cryptellation;
    USE cryptellation_ticks;
    GRANT ALL ON SCHEMA public TO cryptellation;
{{ end }}