apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-ticks
  name: {{ .Release.Name }}-ticks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-ticks
  template:
    metadata:
      annotations:
        {{if (.Values.debug).forceDeployment }}timestamp: {{ now | quote }}{{end}}
      labels:
        app: {{ .Release.Name }}-ticks
    spec:
      containers:
      - name: ticks
        image: {{ ((.Values.services).ticks).image.repository | default "ghcr.io/cryptellation/ticks" }}:{{ ((.Values.services).ticks).image.tag | default (printf "v%s" .Chart.AppVersion) }}
        imagePullPolicy: {{ ((.Values.services).ticks).image.pullPolicy | default "Always" }}
        livenessProbe:
          httpGet:
            path: /liveness
            port: {{ (((.Values.services).ticks).health).port | default 9000 }}
        readinessProbe:
          httpGet:
            path: /readiness
            port: {{ (((.Values.services).ticks).health).port | default 9000 }}
        env:
        # Binance
        - name: "BINANCE_API_KEY"
          valueFrom:
            configMapKeyRef:
              key: binance.api_key
              name: cryptellation-credentials
        - name: "BINANCE_SECRET_KEY"
          valueFrom:
            configMapKeyRef:
              key: binance.secret_key
              name: cryptellation-credentials
        # Health
        - name: "HEALTH_ADDRESS"
          valueFrom:
            configMapKeyRef:
              key:  health.address
              name: cryptellation-ticks
        # Opentelemetry
        - name: "OPENTELEMETRY_GRPC_ENDPOINT"
          valueFrom:
            configMapKeyRef:
              key: opentelemetry.grpc.endpoint
              name: cryptellation-credentials
        # Temporal
        - name: "TEMPORAL_ADDRESS"
          valueFrom:
            configMapKeyRef:
              key: temporal.address
              name: cryptellation-credentials
        resources: {}
status: {}
